config/routes.rb
Rails.application.routes.draw do


  root 'home#index'
  post 'home/send_email', to: 'home#send_email', as: :send_email
  get 'jewelries', to: 'jewelries_pages#index', as: 'jewelries_pages'


  devise_for :admins
  get 'admin', to: 'collections#index'
  scope 'admin' do
    resources :collections do
      collection { post :sort }
    end
    resources :jewelries do
      collection { post :sort }
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collection.rb
class Collection < ApplicationRecord
  scope :with_jewelries, -> { order(:position).includes(:jewelries).where(visible: true) }
  has_many :jewelries, -> { order(:position) }

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
  has_attached_file :title_image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :title_image, content_type: /\Aimage\/.*\z/
end

app/models/jewelry.rb
class Jewelry < ApplicationRecord
  belongs_to :collection

  before_create :increment_position

  has_attached_file :picture, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

  private
    def increment_position
      self.position = Jewelry.all.length + 1
    end
end

app/models/message.rb
class Message
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :message

  validates :name, presence: "can't be blank!"
  validates :email, presence: true
  validates_format_of :email, :with => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates_length_of :message, :maximum => 500

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

end

app/models/user.rb
class User
  attr_accessor :name, :email, :message
end

app/controllers/admin_section_controller.rb
class AdminSectionController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin'
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: :sort
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.order(:position)
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collections_path, notice: 'Collection was successfully created.' }
        format.json { render :show, status: :created, location: @collection }
      else
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def sort
    params[:collection].each_with_index do |id, index|
      Collection.where(id: id).update_all({position: index + 1})
    end
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :visible, :position, :picture, :title_image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @collections = Collection.where(visible: true).order(:position)
  end

  def send_email
    message_params = { name: params[:name], email: params[:email], message: params[:message] }
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.valid?
        ContactMailer.send_email(message_params).deliver
        format.html { redirect_to root_url, notice: "Your message was sent successfully!" }
        format.js
      else
        # puts 'YOYOYOYOYOYOYOYOYOOYOY'
        # @message.errors.full_messages.each {  |e| puts e}
        format.js
      end
    end
  end



end

app/controllers/jewelries_controller.rb
class JewelriesController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!
  skip_before_action :verify_authenticity_token, only: :sort
  before_action :set_jewelry, only: [:show, :edit, :update, :destroy]

  # GET /jewelries
  # GET /jewelries.json
  def index
    @jewelries = Jewelry.order(:position).includes(:collection)
  end

  # GET /jewelries/1
  # GET /jewelries/1.json
  def show
  end

  # GET /jewelries/new
  def new
    @jewelry = Jewelry.new
  end

  # GET /jewelries/1/edit
  def edit
  end

  # POST /jewelries
  # POST /jewelries.json
  def create
    @jewelry = Jewelry.new(jewelry_params)

    respond_to do |format|
      if @jewelry.save
        format.html { redirect_to jewelries_path, notice: 'Jewelry was successfully created.' }
        format.json { render :show, status: :created, location: @jewelry }
      else
        format.html { render :new }
        format.json { render json: @jewelry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jewelries/1
  # PATCH/PUT /jewelries/1.json
  def update
    respond_to do |format|
      if @jewelry.update(jewelry_params)
        format.html { redirect_to jewelries_path, notice: 'Jewelry was successfully updated.' }
        format.json { render :show, status: :ok, location: @jewelry }
        format.js
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /jewelries/1
  # DELETE /jewelries/1.json
  def destroy
    @jewelry.destroy
    respond_to do |format|
      format.html { redirect_to jewelries_url, notice: 'Jewelry was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  def sort
    params[:jewelry].each_with_index do |id, index|
      Jewelry.where(id: id).update_all({position: index + 1})
    end
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jewelry
      @jewelry = Jewelry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jewelry_params
      params.require(:jewelry).permit(:name, :inspiration, :material, :visible, :position, :picture, :collection_id)
    end
end

app/controllers/jewelries_pages_controller.rb
class JewelriesPagesController < ApplicationController
  def index
    @collections = Collection.with_jewelries
  end
end

app/helpers/admin_section_helper.rb
module AdminSectionHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jewelries_helper.rb
module JewelriesHelper
end

app/helpers/jewelries_pages_helper.rb
module JewelriesPagesHelper
end

app/views/admin_section/index.html.erb
<h1>AdminSection#index</h1>
<p>Find me in app/views/admin_section/index.html.erb</p>

app/views/collections/_form.html.erb
<div class="row justify-content-center text-center">
  <div class="col-md-12">
    <%= form_with(model: collection, local: true) do |form| %>
      <% if collection.errors.any? %>
        <div id="error_explanation">
          <div class="alert alert-danger">
            <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>
          </div>
          <ul>
          <% collection.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
        <div class="col-6 mx-auto">
          <div class="form-group">
            <%= form.label :name %>
            <%= form.text_field :name, id: :collection_name, class: 'form-control' %>
          </div>
        </div>

        <% if collection.picture? %>
          <div class="col-6 mx-auto">
            <%= image_tag collection.picture.url, class: 'form-img' %>
          </div>
        <% end %>
        <div class="upload-btn-wrapper">
          <button class="btn btn-custom"><%= collection.picture? ? 'Upload Different Picture' : 'Upload Picture' %></button>
          <%= form.file_field :picture, id: :collection_picture %>
        </div>
        <div class="upload-btn-wrapper">
          <button class="btn btn-custom">Upload Picture</button>
          <%= form.file_field :title_image, id: :collection_title_image %>
        </div>

      <div class="actions">
        <%= form.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/collections/destroy.js.erb
$("#collection-" + <%= @collection.id %>).remove();

app/views/collections/edit.html.erb
<div class="row text-center">
  <div class="col">
    <h1>Editing Collection</h1>

    <%= render 'form', collection: @collection %>

    <%= link_to 'Show', @collection %> |
    <%= link_to 'Back', collections_path %>
  </div>
</div>

app/views/collections/index.html.erb
<div id="collection-index" class="row text-center">
  <div class="col">
    <h1>Collections</h1>
  </div>
</div>
<div class="row text-center marginTop50 marginBottom50">
  <div class="col-12">
    <%= link_to 'Add New Collection', new_collection_path, class: 'add-button' %>

  <div class="sortable row marginTop50" data-update-url="<%= sort_collections_path %>">
    <% @collections.each do |collection| %>
      <div id="collection-<%= collection.id %>" class="col-3 collection-wrapper-div box <%= collection.visible? ? 'box-green' : 'box-red' %>">
        <%= link_to collection do %>
          <%= collection.name %>
          <div class="collections-img-wrapper mx-auto">
            <%= image_tag collection.picture.url %>
            <div class="collections-img-mask"></div>
          </div>
        <% end %>
        <br>
        <%= link_to 'Edit', edit_collection_path(collection), class: 'btn btn-outline-info' %> |
        <%= link_to 'Delete', collection, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger', remote: true %>
        <br>
        <br>
        <p class="current-status">Current Status: <%= link_to(collection.visible? ? 'Visible' : 'Not Visible', collection_path(collection.id, collection: { visible: collection.visible? ? false : true }), class: 'visibility-link', remote: true, method: :put) %></p>
      </div>
    <% end %>
  </div>
  </div>
</div>

app/views/collections/new.html.erb
<div class="row text-center">
  <div class="col">
    <h1>New Collection</h1>

    <%= render 'form', collection: @collection %>

    <%= link_to 'Back', collections_path %>
  </div>
</div>

app/views/collections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @collection.name %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @collection.visible %>
</p>

<p>
  <strong>Position:</strong>
  <%= @collection.position %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @collection.picture %>
</p>

<%= link_to 'Edit', edit_collection_path(@collection) %> |
<%= link_to 'Back', collections_path %>

app/views/collections/update.js.erb
$("#collection-<%= @collection.id %> .current-status").html("Current Status: <%=j link_to(@collection.visible? ? 'Visible' : 'Not Visible', collection_path(@collection.id, collection: { visible: @collection.visible? ? false : true }), class: 'visibility-link', remote: true, method: :put) %>")
<% if @collection.visible? %>
  $("#collection-<%= @collection.id %>").removeClass('box-red').addClass('box-green')
<% else %>
  $("#collection-<%= @collection.id %>").removeClass('box-green').addClass('box-red')
<% end %>

app/views/home/index.html.erb
<div id="home" class="background">
  <div class="container parallax-bg">
    <div class="row">
      <div class="col-12">
        <div class="swiper-container">
            <div class="swiper-wrapper">
                <div class="swiper-slide"><iframe class="video" src="https://player.vimeo.com/video/146656196?autoplay=0&amp;loop=0&amp;color=8D8292&amp;title=0&amp;byline=0&amp;portrait=0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></div>
                <div class="swiper-slide"><%= image_tag 'carousel-1.jpg' %></div>
                <!-- <div class="swiper-slide"><%= image_tag 'carousel-2.jpg' %></div> -->
                <!-- <div class="swiper-slide"><%= image_tag 'carousel-3.jpg' %></div> -->
                <div class="swiper-slide"><%= image_tag 'carousel-4.jpg' %></div>
                <div class="swiper-slide"><%= image_tag 'carousel-5.jpg' %></div>
            </div>
        </div>
        <div class="swiper-pagination"></div>
      </div>
    </div>
  </div>
</div>
<div id="collections" class="background custom-container">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1>COLLECTIONS</h1>
      </div>
    </div>
    <div class="row marginBottom100 parallax-element-detected">
      <% @collections.each do |collection| %>
        <div class="col-lg-3 col-md-6 marginTop50 parallax-element">
          <%= link_to jewelries_pages_path(anchor: collection.name == 'African Mermaid' ? 'African' : collection.name) do %>
            <div class="collections-img-wrapper mx-auto">
              <%= image_tag collection.picture.url(:medium) %>
              <div class="collections-img-mask"></div>
              <p class="collection-name text-center"><%= collection.name %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="inter-section inter-section-1">
  <div class="parallax-bg-2"></div>
</div>
<div id="about" class="background custom-container">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <h1>ABOUT</h1>
      </div>
    </div>
    <div class="row marginTop50 parallax-element-detected">
      <div class="col">
        <p class="parallax-element">
          As far as I can remember, I have always loved creating and working with
          my own hands. I could stayed confined in my bedroom for days to finish
          any type of artistic projects. <br> I took multiple drawing and creation
          design classes as I grew up, each one of them were enriching and
          fulfilling . They made me realize that this is what I wanted to do, this
          is what I wanted to be.
        </p>
        <p class="parallax-element">
          After four years studying in France I obtained a bachelor degree in Jewelry
          Design. At "La SEPR Lyon", where I’ve learned the history of jewelry and
          the transformation of the techniques through ages as well as studying and
          using them for my own purpose. <br> What I love the most about Jewelry
          is finding the inspiration in a lots of very different and unusual domain,
          make it my own then retransform, mix ideas and theme before the realization
          of the piece itself.<br> For about three years I have been experiencing,
          discovering, self teaching and working in various field, trying to express
          my own personality through jewelry creation.
        </p>
        <p class="parallax-element">
          Each piece of jewelry were design and hand made in New York by myself. <br>
          And I finally present to you a part of my work.
        </p>
      </div>
    </div>
    <div class="row marginTop100 marginBottom100 align-items-center parallax-element-detected">
      <div class="col-12 marginBottom50">
        <p class="parallax-element">Who helped me with the video realization?</p>
      </div>
      <div class="col-md-4 col-sm-6 text-center">
        <%= image_tag 'logo-vara.png', class: 'parallax-element logo logo-vara' %>
      </div>
      <div class="col-md-2 col-sm-6 text-center">
        <%= image_tag 'logo-flora.jpg', class: 'parallax-element logo' %>
      </div>
      <div class="col-md-3 col-sm-6 text-center">
        <%= image_tag 'logo-rebecca.jpg', class: 'parallax-element logo' %>
      </div>
      <div class="col-md-3 col-sm-6 text-center">
        <%= image_tag 'logo-renan.png', class: 'parallax-element logo' %>
      </div>
    </div>
  </div>
</div>
<div class="inter-section inter-section-2">
  <div class="parallax-bg-2"></div>
</div>
<div id="contact" class="background custom-container">
  <div class="container">
    <div class="row">
      <div class="col">
        <h1>CONTACT</h1>
      </div>
    </div>
    <div class="row marginTop50 parallax-element-detected">
      <div class="col-12 text-center parallax-element">
        <div class="notice"></div>
        <div class="alert"></div>
        <%= form_tag(send_email_path, remote: true , class: 'form' )  do %>
        Hi Camille,<br><br>
        My name is <%= text_field_tag 'name', nil, placeholder: 'Type Your Name', class: 'form-input name-input' %>
        and I'd like to <span class="dot-wrapper"><%= text_area_tag 'message', nil, placeholder: 'Type A Short Message Here', class: 'form-input form-textarea' %><span class="dot">.</span></span><br><br>
        By the way, my email is <%= email_field_tag 'email', nil, placeholder: 'Type Your Email', class: 'form-input email-input' %>.<br>
        <div class="paper-plane-wrapper">
          <svg class="svg-lines" width="100%" height="100%" viewBox="0 0 800 200" xmlns="http://www.w3.org/2000/svg">
            <path id="trail" d="M6.044,73.835c0,0 68.026,-38.204 186.291,-36.833c90.058,1.045 132.836,32.117 157.582,51.596c47.589,37.458 10.037,66.43 -9.357,65.595c-15.835,-0.681 -44.514,-14.884 -31.322,-44.376c35.135,-78.553 158.913,-91.491 278.881,-37.206c67.246,30.428 165.956,50.908 245.957,-66.278" stroke="#000" stroke-width="2" fill="none"style="stroke-dashoffset: 1500px; stroke-dasharray: 1500px;" />
            <path d="M6.044,73.835c0,0 68.026,-38.204 186.291,-36.833c90.058,1.045 132.836,32.117 157.582,51.596c47.589,37.458 10.037,66.43 -9.357,65.595c-15.835,-0.681 -44.514,-14.884 -31.322,-44.376c35.135,-78.553 158.913,-91.491 278.881,-37.206c67.246,30.428 165.956,50.908 245.957,-66.278" stroke="#fff" stroke-width="3" fill="none"style="stroke-dasharray: 10px;" />
          </svg>
          <svg class="svg-plane" width="100%" height="200" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
            <path id="plane" d="M72.43,118.924l-31.128,34.551l9.875,-57.638l-47.534,-41.568l268.174,-51.444l-150.807,184.268l-48.58,-68.169l199.387,-116.099l-220.64,93.012l-9.875,57.638l44.602,-15.644" style="fill:none;stroke:#000;stroke-width:3.5px;stroke-dashoffset: 2000px;stroke-dasharray: 2000px;"/>
          </svg>

          <%= submit_tag 'SEND', class: 'form-submit' %>
        </div>
        <% end %>
        <%= form_tag(send_email_path, remote: true, class: 'form-mobile' ) do %>
          <div class='form-group'>
            <%= text_field_tag 'name', nil, placeholder: 'Name', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= email_field_tag 'email', nil, placeholder: 'Email', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= text_area_tag 'message', nil, placeholder: 'A Short Message', rows: 5, class: 'form-control' %>
          </div>
          <%= submit_tag 'SEND', class: 'form-submit' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jewelries/destroy.js.erb
$("#jewelry-<%= @jewelry.id %>").remove();

app/views/jewelries/edit.html.erb
<div class="row text-center">
  <div class="col">
    <h1>Editing Jewelry</h1>

    <%= render 'form', jewelry: @jewelry %>

    <%= link_to 'Show', @jewelry %> |
    <%= link_to 'Back', jewelries_path %>
  </div>
</div>

app/views/jewelries/index.html.erb
<div id="jewelry-index" class="row text-center">
  <div class="col-12">
    <h1>Jewelries</h1>
  </div>
  <div class="col-12 marginTop50">
    <%= link_to 'Add New Jewelry', new_jewelry_path, class: 'add-button' %>
  </div>
  <div class="col-12 marginTop50">
    <table class="table table-hover">
      <thead>
        <tr>
          <th colspan="1"><%= image_tag 'icon-drag.png', class: 'image-thumb-drag' %></th>
          <th>#</th>
          <th>Name</th>
          <th>Picture</th>
          <th>Inspiration</th>
          <th>Material</th>
          <th>Collection</th>
          <th>Visible</th>
          <th colspan="3">Action</th>
        </tr>
      </thead>

      <tbody class="vertical-sortable" data-update-url="<%= sort_jewelries_path %>">
        <% @jewelries.each do |jewelry| %>
          <tr id="jewelry-<%= jewelry.id %>">
            <td class="drag-handle"><%= image_tag 'icon-drag-handle.png', class: 'image-thumb-handle' %></td>
            <td class="jewelry-position"><%= jewelry.position %></td>
            <td><%= jewelry.name %></td>
            <td><%= image_tag jewelry.picture.url(:thumb) %></td>
            <td><%= jewelry.inspiration %></td>
            <td><%= jewelry.material %></td>
            <td><%= jewelry.collection.name %></td>
            <td class="visible-column <%= jewelry.visible? ? 'box-green' : 'box-red' %>"><%= link_to jewelry.visible? ? 'Yes' : 'No', jewelry_path(jewelry, jewelry: { visible: jewelry.visible? ? 'false' : 'true' }), class: 'toggle-visibility', method: :put, remote: true %></td>
            <td><%= link_to 'View', jewelry, class: 'btn btn-outline-success' %></td>
            <td><%= link_to 'Edit', edit_jewelry_path(jewelry), class: 'btn btn-outline-info' %></td>
            <td><%= link_to 'Delete', jewelry, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger', remote: true %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/jewelries/new.html.erb
<div class="row text-center">
  <div class="col">
    <h1>New Jewelry</h1>

    <%= render 'form', jewelry: @jewelry %>

    <%= link_to 'Back', jewelries_path %>
  </div>
</div>

app/views/jewelries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @jewelry.name %>
</p>

<p>
  <strong>Inspiration:</strong>
  <%= @jewelry.inspiration %>
</p>

<p>
  <strong>Material:</strong>
  <%= @jewelry.material %>
</p>

<p>
  <strong>Visible:</strong>
  <%= @jewelry.visible %>
</p>

<p>
  <strong>Position:</strong>
  <%= @jewelry.position %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @jewelry.picture %>
</p>

<p>
  <strong>Collection:</strong>
  <%= @jewelry.collection %>
</p>

<%= link_to 'Edit', edit_jewelry_path(@jewelry) %> |
<%= link_to 'Back', jewelries_path %>

app/views/jewelries/sort.js.erb
var positions = $.find(".jewelry-position");
positions.forEach(function(position, index) {
  $(position).html(index + 1)
});

app/views/jewelries/update.js.erb
var column = $("#jewelry-<%= @jewelry.id %> .visible-column");
var columnLink = $("#jewelry-<%= @jewelry.id %> .visible-column a");
column.html("<%=j link_to @jewelry.visible? ? 'Yes' : 'No', jewelry_path(@jewelry, jewelry: { visible: @jewelry.visible? ? 'false' : 'true' }), class: 'toggle-visibility', method: :put, remote: true %>")
<% if @jewelry.visible? %>
  column.removeClass('box-red').addClass('box-green');
  columnLink.html('Yes')
<% else %>
  column.removeClass('box-green').addClass('box-red');
  columnLink.html('No')
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkubichJewelry-Admin</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="admin">
    <nav class="navbar navbar-expand-md fixed-top navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to(image_tag('logo-nav.png'), root_path, class: 'navbar-brand')  %>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div id="navbar" class="navbar-nav">
          <%= link_to 'Website', root_path, class: 'nav-item nav-link' %>
          <%= link_to 'LogOut', destroy_admin_session_path, method: :delete, class: 'nav-item nav-link' %>
        </div>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="admin-side-bar">
      <ul>
        <li class="<%= 'active' if request.path_info.include?('collection') %>"><%= link_to 'Collections', collections_path %></li>
        <li class="<%= 'active' if request.path_info.include?('jewel') %>"><%= link_to 'Jewelries', jewelries_path %></li>
      </ul>
    </div>
    <div class="custom-container-admin">
      <div class="container">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SkubichV2</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id='devise'>
    <nav class="navbar navbar-expand-md fixed-top navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to(image_tag('logo-nav.png'), root_path, class: 'navbar-brand')  %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
    <!-- <footer class="text-center">
      <p>Site by <a href="http://www.channedesign.com" target="_blank">Channe</a> | &copy; Camille Skubich Jewelry</p>
    </footer> -->
  </body>
</html>